TILE_SIZE = 32
SECONDS_BETWEEN_ACTIONS = 0.1
MAX_FPS = 60
HEALTH_DEPLETION = 5
MAX_HEALTH = 100

DEBUG = False

TILE_MAP_START_Y = 0

TARGET_SCREEN_WIDTH = 1920 // 5
TARGET_SCREEN_HEIGHT = 1080 // 5

TILE_NUMBER_WIDTH = TARGET_SCREEN_WIDTH // TILE_SIZE  # 30
TILE_NUMBER_HEIGHT = TARGET_SCREEN_HEIGHT // TILE_SIZE  # 16

SCREEN_WIDTH = TILE_NUMBER_WIDTH * TILE_SIZE  # 1920
SCREEN_HEIGHT = TILE_NUMBER_HEIGHT * TILE_SIZE # 1024
